# Generated by Django 6.0.2 on 2026-04-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='story',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='stories/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_file',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
